#
# Test build of HAProxy on ARM64
# 

name: ARM64 via QEMU

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Register QEMU
      run: |
        sudo docker run --rm --privileged multiarch/qemu-user-static --reset --credential yes --persistent yes
    - name: Build ARM64 Docker container
      run: |
        docker build aarch64/ -t haproxy-aarch64:latest
    - name: Build and test on ARM64
      run: |
        docker run --rm haproxy-aarch64:latest
